Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column)

In [7]:
import numpy as np

In [2]:
np.array(any list)           #converts list to array
np.arange(0,5,2)             #makes array based on range, 3rd argu is step size
np.zeros((4,4))              
np.ones((3,3))
np.linspace(0,10,3)
np.eye(4)                    #Identity matrix, diagonal 1's
np.random.random()           #gives random value
np.random.rand(5,4)          #matrix of random number uniform distribution
np.random.randn(4,4)         #same but standard distribution
np.random.randint(2,100,10)  #random integer between range
np.random.seed(1)            #gives same random value
np.random.uniform(x,y,z)     #gives array of random values,x and y is range, z is size
np.hstack((arrvar1,arrvar2)) #stacks two arrays, h = horizontal, v = vertical
np.hsplit(arrvar,2)          #splits array into equal parts, number is parts, h and v
np.where(condition,if true   #to store new array in different variable
        , if false)
np.sort(arrvar)
np.percentile(arrvar,25)     #gives value based on percentile value passed
1D arrvar.reshape(5,5)       #converts 1D array to 2D matrix
arrvar.ravel()               #turns n-D array to 1D array
arrvar.max(axis)             #axis gives max/min of each row/column
arrvar.min()
arrvar.argmax/min()          #same as min,max but gives index position
arrvar[[r,r,r],[c,c,c]]      #gives rows/columns based on row/column number / fancy indexing

np.sum(arrvar) or            #To get sum of all elements inside
arrvar.sum()
arrvar.copy(arrvar2)         #copies array
arrvar.astype('data type')   #Converts the array into passed data type
arrvar.dot(arrvar2)          #dot matrix multiplication
arrvar.transpose()           #converts (2,3) shape array to (3,2), switches rows and columns


#ATTRIBUTES
arrvar.shape                 #no brackets and gives no. of columns and rows
arrvar.dtype                 #no brackets, gives datatype of array
arrvar.ndim                  #gives dimensions of array
arrvar.size                  #gives size(no. of items in array)
arrvar.itemsize              #C O N F U S I O N https://youtu.be/ikx70DFC2T8?t=329
arrvar.itemsize * arrvar.size #memory occupied by array
np.nditer(arrvar)            #iteration to get each item in array




#arrvar = array variable




#https://youtu.be/7VVZIkCcTHU?t=582  arrvar.sum() vs np.sum(arrvar)
#https://youtu.be/f7mcmDm7QFs - to calculate time and memory size
#how to know that when to pass values as list or tuples?
& vs and , bitwise
#Broadcasting array https://youtu.be/LaKAA7Z84so

SyntaxError: invalid syntax (645366801.py, line 1)

In [ ]:
np.zeros((5,5))
np.ones((2,2))
#pay attention to brackets, its a tuple.         

In [ ]:
np.linspace(0,10,3)
#evenly spaced points based on third arguement
#one-dimensional array

Array copies arent created unless you mention
any array = arr.copy #This will create a new copy of array

**Array slicing and grabbing

In [ ]:
arange = np.arange(20)
x = arange.reshape(4,5)
x

In [ ]:
x[1,2]
#for single value

In [ ]:
x[1:3,2:4]
#for a range of values

**Conditional selection

In [ ]:
#Gives boolean values based on conditions
x>10

In [ ]:
x[x>10]

In [ ]:
arr2d = np.zeros((10,10))

In [ ]:
#DOUBT
arr2d

In [ ]:
arr_length = arr2d.shape[1]

In [ ]:
arr_length

In [ ]:
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

.

**Arithmetic operation on arrays

In [ ]:
g = np.arange(10)
g

In [ ]:
g+g
#g-g, g*g, g/g

In [ ]:
g + 10
#g-2, g*4

In [4]:
ab = np.arange(10)
ab.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

https://docs.scipy.org/doc/numpy-1.9.3/reference/ufuncs.html

In [6]:
for i in np.nditer(ab):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [11]:
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
a[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [13]:
  #SELF - FUNCTION TO GET SUM IN ARRAY
def sum_array(arr):
    sum = 0
    for i in np.nditer(arr):
        sum = sum+i
    return sum

In [14]:
sum_array(np.arange(0,10).reshape(5,2))

45

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [17]:
a.sum()

45